[workspace]
authors = ["canoziia <canoziia@projectk.org>"]
channels = ["conda-forge"]
name = "homework-1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-deps = """
npx playwright install firefox --with-deps
"""
start = "python src/main.py"

[dependencies]
python = ">=3.13.7,<3.14"
pip = ">=25.2,<26"
uv = ">=0.8.18,<0.9"

[pypi-dependencies]
cmd2 = ">=2.7.0, <3"
llama-index = ">=0.14.0,<0.15"
llama-index-llms-openai-like = ">=0.5.1, <0.6"
torch = ">=2.8.0, <3"
llama-index-tools-mcp = ">=0.3.0, <0.4"
mcp-proxy = ">=0.9.0, <0.10"
