[workspace]
authors = ["canoziia <canoziia@projectk.org>"]
channels = ["conda-forge"]
name = "homework-1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "python src/main.py"

[dependencies]
python = ">=3.13.7,<3.14"
pip = ">=25.2,<26"

[pypi-dependencies]
cmd2 = ">=2.7.0, <3"
llama-index = ">=0.14.3,<0.15"
llama-index-llms-openai-like = ">=0.5.1, <0.6"
torch = ">=2.8.0, <3"
